# SETTINGS
app:
  external-url: http://localhost:8080
  password-token-expiration-hours: 2

#GENERAL
spring:
  application.name: CrudCadastro

#DATA SOURCE
  datasource:
    hikari.pool-name: cadastro
    hikari.maximum-pool-size: 3
    url: jdbc:postgresql://127.0.0.1:5432/cadastro
    username: postgres
    password: postgres

#JPA
  jpa:
    #hibernate.ddl-auto: create
    hibernate.ddl-auto: validate
    show-sql: true
    open-in-view: true



